# Generated by Django 4.0.3 on 2022-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
